### ISSUE TITLE
🚀 功能改善

### ISSUE THREAD

**Issue by ichendaye** [ConnectAI-E/WeWork-OpenAI-Node#10]
# 功能改善建议 🚀

回复的markdown消息未正常渲染

## 您的建议是什么？ 🤔

渲染markdown消息

**Comment by sytpb** [comment]
https://github.com/sytpb/chatgpt-wework-robot   还未同步过来。

**Comment by ichendaye** [comment]
坐等更新

**Comment by sytpb** [comment]
后期会移过来，着急可以先参考上面的
