### ISSUE TITLE
🐞 错误报告

### ISSUE THREAD

**Issue by ZaleYC** [ConnectAI-E/WeWork-OpenAI-Node#11]
# 错误报告 🐞

如果您在使用此项目时遇到了错误，请在此报告，我们会尽快解决此问题。

## 错误描述 🤔

当openAI返回消息存在英文字符，如 ! 时，企业微信会转义为%21,这个如何解决呢？

## 附加信息 📝

请提供以下信息以帮助我们更快地解决问题：

- 输出日志，包括错误信息和堆栈跟踪
- 相关的代码片段或文件
- 您的操作系统、软件版本等环境信息

感谢您的反馈！🙏

**Comment by sytpb** [comment]
https://github.com/sytpb/chatgpt-wework-robot 参考这里。

**Comment by ZaleYC** [comment]
谢谢！
