### ISSUE TITLE
🐞 错误报告

### ISSUE THREAD

**Issue by ichendaye** [ConnectAI-E/WeWork-OpenAI-Node#9]
# 错误报告 🐞

未正确回复内容

## 错误描述 🤔

docker日志里已经返回了数据，但是企业微信里还是显示的正在生成回答

**Comment by ichendaye** [comment]
忘了配置白名单了

**Comment by sytpb** [comment]
COOL , 能不能把你的docker 部署经验分享出来？ 现在docker 部署还不是很详细，需要完善。

**Comment by ichendaye** [comment]
就是按照你的文档弄的，只是变量文件不完整，需要去你的源码里找.env.example文件来参考

**Comment by sytpb** [comment]
需要让从来没用过docker的人，看完就能部署成功。
